/aruco_left_node:
  ros__parameters:
    marker_size: 0.015
    aruco_dictionary_id: DICT_4X4_250
    image_topic: /left/image_rect
    camera_info_topic: /left/camera_info


/aruco_right_node:
  ros__parameters:
    marker_size: 0.015
    aruco_dictionary_id: DICT_4X4_250
    image_topic: /right/image_rect
    camera_info_topic: /right/camera_info